CHUNKING_FLAG = False
EMBEDDING_FLAG = False

BINARY = True

CREATE_BINARY_DATASET_FLAG = True
CALIBRATE_FLAG = False

NUM_DESIRED_SAMPLES = 500
MAX_DESIRED_SAMPLES_PER_COMMENT = 5
NUM_DESIRED_AUTHORS = 10

FIT_FLAG = True
MODEL_LOAD_NAME = "NONE"